[CORE]
core_version="3.0"

[DATA_NODE.conversion_input]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.convert_files]
inputs = [ ]
outputs = [ ]
function = ""
skippable = "False:bool"

[SCENARIO.SCENARIO_1]
additional_data_nodes = [ ]
tasks = [ ]

[SCENARIO.SCENARIO_1.sequences]
SEQUENCE_1 = []
