# Python BASE
FROM python:3.12-slim AS builder

# Install on Debian
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    unzip && \
    apt-get clean

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry


# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY . .

ENV PYTHON_VENV="/app/mine2sirius_venv"

# Install Python dependencies listed in pyproject.toml
RUN python -m venv --copies $PYTHON_VENV && \
    poetry config virtualenvs.in-project true && \
    . $PYTHON_VENV/bin/activate && \
    poetry lock --no-update && \
    poetry install --no-root


# INSTALL external dependencies
# Install MZmine
ENV MZMINE_DIR=/app/mzmine

RUN mkdir -p $MZMINE_DIR && chmod -R +w $MZMINE_DIR && \
    curl -L https://github.com/mzmine/mzmine/releases/download/v4.4.3/mzmine_Linux_portable-4.4.3.zip -o mzmine.zip && \
    unzip mzmine.zip -d $MZMINE_DIR && \
    chmod -R +x $MZMINE_DIR/* && \
    rm mzmine.zip

ENV PATH="$PATH:$MZMINE_DIR/bin"

# Install Sirius
ENV SIRIUS_DIR=/app/sirius

RUN mkdir -p $SIRIUS_DIR  && chmod -R +w $MZMINE_DIR &&  \
    curl -L https://github.com/sirius-ms/sirius/releases/download/v6.0.7/sirius-6.0.7-linux64.zip -o sirius.zip && \
    unzip sirius.zip -d $SIRIUS_DIR && \
    mv $SIRIUS_DIR/sirius/* $SIRIUS_DIR && \
    rm -d $SIRIUS_DIR/sirius && \
    chmod -R +x $SIRIUS_DIR/* && \
    rm sirius.zip

ENV PATH="$PATH:$SIRIUS_DIR/bin"


# Import Proteowizard
FROM chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:3.0.24284-bc93c28

RUN apt-get update && apt-get install -y \
    tree \
    build-essential \
    libffi-dev \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    liblzma-dev

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY --from=builder /app /app

# Define alias for msconvert
RUN echo '#!/bin/bash\nwine msconvert' > /usr/bin/msconvert && \
    chmod +x /usr/bin/msconvert

# Define aliases for other programs
ENV PATH="$PATH:$MZMINE_DIR/bin:$SIRIUS_DIR/bin"


RUN python --version



# Specify the command to run when the container starts
CMD ["python", "-m", "source.gui.main"]
