[GLOBAL]
pants_version = "2.23.1"
backend_packages = [
    "pants.backend.build_files.fmt.ruff",
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.docker",
    "pants.backend.shell"
]

[source]
root_patterns = [
    '/',
]