[build-system]
requires = [ "poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "mine2sirius-pipe"
description = "An integrated workflow to extract (novel) outlier metabolites from MS data."
requires-python = ">=3.12"
dependencies = []
authors = [ { name = "Josua Carl", email = "josua.carl@uni-tuebingen.de" } ]
readme = {file = "README.txt", content-type = "text/markdown"}
license = {file = "LICENSE" }
keywords = ["mass-spectrometry", "workflow", "pipeline", "gui", "sirius", "mzmine" ]

[tool.poetry]
name = "mine2sirius-pipe"
version = "2024.2.1"
description = "mzMine to SIRIUS pipeline"
authors = ["JosuaCarl <josua.carl@uni-tuebingen.de>"]
license = "GPL-3.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
scipy = "^1.14.1"
pyarrow = "^17.0.0"
jupyter = "^1.1.1"
tqdm = "^4.66.5"
dask = "^2024.9.1"
argparse = "^1.4.0"
sphinx = "^7"
regex = "^2024.9.11"
beautifulsoup4 = "^4.12.3"
lxml = "^5.3.0"
pandas = "^2.2.2"
pydata-sphinx-theme = "^0.15.4"
statsmodels = "^0.14.4"
seaborn = "^0.13.2"
plotly = "^5.24.1"
requests = "^2.32.3"
tee-subprocess = "^1.2.0"
pyopenms = "3.2.0.1"
chardet = "^5.2.0"
multipledispatch = "^1.0.0"
taipy = "^4.0.1"
ruamel-yaml = "^0.18.6"

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"
icecream = "^2.1.3" 
ruff = "^0.8.1"

# Ruff rules
[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = [ "F403", "F405" ]

[tool.ruff]
line-length = 100