[tool.poetry]
name = "mine2sirius-pipe"
version = "0.1.0"
description = "mzMine to SIRIUS pipeline"
authors = ["JosuaCarl <josua.carl@student.uni-tuebingen.de>"]
license = "GPL-3.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.8.2"
numpy = "^2.1.1"
scipy = "^1.14.1"
pyarrow = "^17.0.0"
jupyter = "^1.1.1"
tqdm = "^4.66.5"
dask = "^2024.9.1"
argparse = "^1.4.0"
pytest = "^8.3.3"
sphinx = "^7"
sphinx-rtd-theme = "^2.0.0"
regex = "^2024.9.11"
beautifulsoup4 = "^4.12.3"
lxml = "^5.3.0"
pandas = "^2.2.3"
pydata-sphinx-theme = "^0.15.4"
statsmodels = "^0.14.4"
seaborn = "^0.13.2"
plotly = "^5.24.1"
requests = "^2.32.3"
tee-subprocess = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
