[CORE]
core_version="3.0"

[DATA_NODE.raw_data]
storage_type = "generic"
scope = "SCENARIO:SCOPE"

[TASK.convert_files]
inputs = [ "raw_data:SECTION", "args_convert:SECTION" ]
outputs = [ "community_formatted_data:SECTION" ]
function = "source.conversion.msconv_pipe.main:function"
skippable = "False:bool"

[SCENARIO.MS_analysis]
additional_data_nodes = [ ]
tasks = [
  "convert_files:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION",
  "analysis:SECTION"
]

[SCENARIO.MS_analysis.sequences]
all_steps = [
  "analysis:SECTION",
  "convert_files:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION"
]
process_to_analysis = [
  "analysis:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION"
]
annotate_analysis = [
  "analysis:SECTION",
  "gnps_annotation:SECTION",
  "sirius_annotation:SECTION"
]
convert_to_annotate = [
  "convert_files:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION"
]
process_to_annotate = [
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION"
]

[DATA_NODE.community_formatted_data]
storage_type = "generic"
scope = "SCENARIO:SCOPE"

[DATA_NODE.processed_data]
storage_type = "generic"
scope = "SCENARIO:SCOPE"

[DATA_NODE.gnps_annotations]
storage_type = "generic"
scope = "SCENARIO:SCOPE"

[DATA_NODE.sirius_anntations]
storage_type = "generic"
scope = "SCENARIO:SCOPE"

[TASK.find_features]
inputs = [ "community_formatted_data:SECTION", "args_feature_finding:SECTION" ]
outputs = [ "processed_data:SECTION" ]
function = "source.conversion.msconv_pipe.main:function"
skippable = "False:bool"

[TASK.gnps_annotation]
inputs = [ "processed_data:SECTION", "args_gnps:SECTION" ]
outputs = [ "gnps_annotations:SECTION" ]
function = "source.annotation.gnps_pipe.main:function"
skippable = "False:bool"

[TASK.sirius_annotation]
inputs = [ "processed_data:SECTION", "args_sirius:SECTION" ]
outputs = [ "sirius_anntations:SECTION" ]
function = "source.annotation.sirius_pipe.main:function"
skippable = "False:bool"

[DATA_NODE.args_convert]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.results]
storage_type = "csv"
scope = "SCENARIO:SCOPE"

[TASK.analysis]
inputs = [
  "processed_data:SECTION",
  "gnps_annotations:SECTION",
  "sirius_anntations:SECTION",
  "args_analysis:SECTION"
]
outputs = [ "results:SECTION" ]
function = "source.population_difference_testing.statistics.execute_test:function"
skippable = "True:bool"

[DATA_NODE.args_feature_finding]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.args_sirius]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.args_gnps]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.args_analysis]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"
