[CORE]
core_version="3.0"

[DATA_NODE.raw_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.convert_files]
inputs = [ "raw_data:SECTION" ]
outputs = [ "community_formatted_data:SECTION" ]
function = "source.conversion.msconv_pipe.main:function"
skippable = "False:bool"

[SCENARIO.SCENARIO_1]
additional_data_nodes = [ "args:SECTION" ]
tasks = [ "convert_files:SECTION", "process_data:SECTION" ]

[SCENARIO.SCENARIO_1.sequences]
SEQUENCE_1 = []

[DATA_NODE.community_formatted_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.processed_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.gnps_annotations]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.sirius_anntations]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.process_data]
inputs = [ "community_formatted_data:SECTION", "raw_data:SECTION" ]
outputs = [ "processed_data:SECTION" ]
function = ""
skippable = "False:bool"

[TASK.gnps_annotation]
inputs = [ ]
outputs = [ ]
function = ""
skippable = "False:bool"

[TASK.sirius_annotation]
inputs = [ ]
outputs = [ ]
function = ""
skippable = "False:bool"

[DATA_NODE.args]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
