[CORE]
core_version="3.0"

[DATA_NODE.raw_data]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[TASK.convert_files]
inputs = [ "raw_data:SECTION", "ms_analysis_configuration:SECTION" ]
outputs = [ "community_formatted_data:SECTION" ]
function = "source.gui.main.convert_files:function"
skippable = "True:bool"

[SCENARIO.MS_analysis]
additional_data_nodes = [ ]
tasks = [
  "convert_files:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION",
  "analysis:SECTION"
]

[SCENARIO.MS_analysis.sequences]
all_steps = [
  "analysis:SECTION",
  "convert_files:SECTION",
  "gnps_annotation:SECTION",
  "find_features:SECTION",
  "sirius_annotation:SECTION"
]
conv = [ "convert_files:SECTION" ]

[DATA_NODE.community_formatted_data]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.processed_data]
storage_type = "in_memory"
scope = "SCENARIO:SCOPE"

[DATA_NODE.gnps_annotations]
storage_type = "csv"
scope = "SCENARIO:SCOPE"

[DATA_NODE.sirius_anntations]
storage_type = "csv"
scope = "SCENARIO:SCOPE"

[TASK.find_features]
inputs = [
  "community_formatted_data:SECTION",
  "ms_analysis_configuration:SECTION"
]
outputs = [ "processed_data:SECTION" ]
function = "source.conversion.msconv_pipe.main:function"
skippable = "False:bool"

[TASK.gnps_annotation]
inputs = [
  "processed_data:SECTION",
  "ms_analysis_configuration:SECTION"
]
outputs = [ "gnps_annotations:SECTION" ]
function = "source.annotation.gnps_pipe.main:function"
skippable = "False:bool"

[TASK.sirius_annotation]
inputs = [ "processed_data:SECTION", "ms_analysis_configuration:SECTION" ]
outputs = [ "sirius_anntations:SECTION" ]
function = "source.annotation.sirius_pipe.main:function"
skippable = "False:bool"



[DATA_NODE.results]
storage_type = "csv"
scope = "SCENARIO:SCOPE"

[TASK.analysis]
inputs = [
  "processed_data:SECTION",
  "gnps_annotations:SECTION",
  "sirius_anntations:SECTION",
  "ms_analysis_configuration:SECTION"
]
outputs = [ "results:SECTION" ]
function = "source.population_difference_testing.statistics.execute_test:function"
skippable = "True:bool"



[DATA_NODE.ms_analysis_configuration]
storage_type = "json"
scope = "SCENARIO:SCOPE"




