plugin_repo(
  name = "python",
  revision = "v1.12.2",
  plugin = "python-rules",
  owner = "please-build",
)
plugin_repo(
  name = "docker",
  revision = "v0.1.0",
  plugin = "docker-rules",
  owner = "please-build",
)
