name: Deployment of executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.5.15"
          enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install project dependencies
      run: |
        uv sync --all-extras --all-groups
  
    - name: Use Nuitka to compile exe
      run: |
          uv run --frozen python -m nuitka --static-libpython=no --standalone --onefile source/__main__.py
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }} build
        path: |
          build/*.exe
          build/*.bin
          build/*.app/**/*
        include-hidden-files: true

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            LICENSE.txt
