name: Deployment of executables

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'rampt.zip'
        exclusions: '*.git* /*github/* /*tests/* /*docs/* uv.lock Contribute.md'

    - uses: actions/upload-artifact@v4
      with:
        name: rampt.zip
        path: ./rampt.zip
  
  build_installer:
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os: [ {os: ubuntu-latest, name: linux}, {os: windows-latest, name: windows}, {os: macos-latest, name: macos} ]
    steps:
    - uses: actions/checkout@master

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.5.15"
          enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install project dependencies
      run: |
        uv sync

    - name: "Make installer"
      run: |
        uv run pyinstaller --noconfirm --clean --onefile --windowed --name installer_${{ matrix.os.name }} --contents-directory .  rampt/installer.py
      
    - uses: actions/upload-artifact@v4
      with:
        name: rampt_installer_${{ matrix.os.name }}
        path: dist/installer_${{ matrix.os.name }}

    - uses: actions/upload-artifact@v4
      with:
        name: rampt_installer_${{ matrix.os.name }}
        path: dist/installer_${{ matrix.os.name }}.exe

  deploy:
    needs: [ build, build_installer ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    
    - uses: actions/download-artifact@v4
      with:
        name: rampt.zip
        path: dist/rampt.zip

    - uses: actions/download-artifact@v4
      with:
        name: rampt_installer_linux
        path: dist/rampt_installer_linux
    

    - uses: actions/download-artifact@v4
      with:
        name: rampt_installer_macos
        path: dist/rampt_installer_macos

    - uses: actions/download-artifact@v4
      with:
        name: rampt_installer_windows
        path: dist/rampt_installer_windows.exe

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/rampt_installer_linux,dist/rampt_installer_windows.exe,dist/rampt_installer_macos,dist/rampt.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}