name: Deployment of executables

on: 
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: See tags
      run: |
        git tag -l | cat 
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'rampt.zip'
        exclusions: '*.git* /*github/* tests/* docs/* CHANGELOG.md Contribute.md README.md'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "rampt.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}