name: Deployment of executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'rampt.zip'
        exclusions: '*.git* /*github/* .tests .docs CHANGELOG.md Contribute.md README.md'
  
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: latest
        artifacts: "rampt.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}