name: Python Package management with Conda and Poetry

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Enter conda environment
      run: |
        conda create --n mine2sirius python=3.12
        conda activate mine2sirius

   - name: Install dependencies
      run: |
        poetry lock --no-update
        poetry install
    
    - name: Ruff checking
      run: |
        ruff check --output-format=github
